name = "Fourdfp"
uuid = "23cab71e-c09d-4758-9ab0-2c183091423d"
authors = ["Michael Myers"]
version = "1.0.1"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"

[compat]
julia = "1.6.7"
Chain = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
